DEMO_COMPANY = {
    "name": "TechStartup Inc",
    "domain": "techstartup.io",
    "industry": "SaaS",
    "employee_count": 150,
}

DEMO_ASSETS = [
    {
        "name": "prod-api-gateway",
        "asset_type": "api",
        "ip_address": "52.14.88.101",
        "os": "Ubuntu 22.04",
        "services": ["nginx:1.18.0", "node:18.12"],
        "risk_score": 8.9,
        "status": "critical",
        "cve_ids": ["CVE-2023-44487", "CVE-2021-41773"],
        "pos_x": 400.0,
        "pos_y": 100.0,
    },
    {
        "name": "prod-db-postgres",
        "asset_type": "database",
        "ip_address": "10.0.1.50",
        "os": "Ubuntu 20.04",
        "services": ["postgresql:13.8"],
        "risk_score": 9.1,
        "status": "critical",
        "cve_ids": ["CVE-2022-2625"],
        "pos_x": 600.0,
        "pos_y": 300.0,
    },
    {
        "name": "auth-service",
        "asset_type": "server",
        "ip_address": "10.0.1.20",
        "os": "Amazon Linux 2",
        "services": ["python:3.9", "redis:7.0"],
        "risk_score": 7.2,
        "status": "warning",
        "cve_ids": ["CVE-2023-28858"],
        "pos_x": 200.0,
        "pos_y": 300.0,
    },
    {
        "name": "aws-s3-data-bucket",
        "asset_type": "cloud",
        "ip_address": None,
        "os": None,
        "services": ["AWS S3"],
        "risk_score": 6.5,
        "status": "warning",
        "cve_ids": [],
        "pos_x": 700.0,
        "pos_y": 100.0,
    },
    {
        "name": "corp-firewall",
        "asset_type": "firewall",
        "ip_address": "203.0.113.1",
        "os": "Cisco IOS 15.2",
        "services": ["iptables"],
        "risk_score": 5.5,
        "status": "moderate",
        "cve_ids": [],
        "pos_x": 100.0,
        "pos_y": 200.0,
    },
    {
        "name": "dev-workstation-john",
        "asset_type": "endpoint",
        "ip_address": "10.0.2.15",
        "os": "Windows 11 22H2",
        "services": ["chrome:118", "vscode:1.84"],
        "risk_score": 6.8,
        "status": "warning",
        "cve_ids": ["CVE-2023-36025"],
        "pos_x": 200.0,
        "pos_y": 500.0,
    },
    {
        "name": "admin-user-sarah",
        "asset_type": "user",
        "ip_address": None,
        "os": None,
        "services": [],
        "risk_score": 7.5,
        "status": "warning",
        "cve_ids": [],
        "pos_x": 350.0,
        "pos_y": 500.0,
    },
    {
        "name": "payment-processor-api",
        "asset_type": "api",
        "ip_address": "52.14.99.200",
        "os": "Ubuntu 22.04",
        "services": ["nginx:1.24", "python:3.11"],
        "risk_score": 8.3,
        "status": "critical",
        "cve_ids": ["CVE-2023-44487"],
        "pos_x": 550.0,
        "pos_y": 100.0,
    },
]

DEMO_ATTACK_PATHS = [
    {
        "name": "Phishing → Admin Compromise → Full DB Exfil",
        "description": "Social engineering targeting admin user leads to full database compromise and data exfiltration",
        "severity": "critical",
        "mitre_tactics": ["TA0001", "TA0003", "TA0008", "TA0010"],
        "likelihood": 0.72,
        "impact": 0.95,
        "steps": [
            {
                "step_number": 1,
                "asset_name": "admin-user-sarah",
                "technique_id": "T1566.001",
                "technique_name": "Spearphishing Attachment",
                "description": "Admin receives targeted phishing email with malicious attachment containing trojan",
            },
            {
                "step_number": 2,
                "asset_name": "dev-workstation-john",
                "technique_id": "T1078",
                "technique_name": "Valid Accounts",
                "description": "Credential theft via keylogger enables lateral movement to developer machine",
            },
            {
                "step_number": 3,
                "asset_name": "auth-service",
                "technique_id": "T1550.001",
                "technique_name": "Application Access Token",
                "description": "Auth tokens extracted from compromised workstation via memory dump",
            },
            {
                "step_number": 4,
                "asset_name": "prod-db-postgres",
                "technique_id": "T1005",
                "technique_name": "Data from Local System",
                "description": "Full database dump exfiltrated (PII, payment data, customer records)",
            },
        ],
        "source_asset_id": None,
        "target_asset_id": None,
    },
    {
        "name": "API Exploit → RCE → Cloud Storage Exfil",
        "description": "HTTP/2 Rapid Reset vulnerability exploited for RCE, leading to S3 data theft",
        "severity": "high",
        "mitre_tactics": ["TA0001", "TA0002", "TA0010"],
        "likelihood": 0.45,
        "impact": 0.80,
        "steps": [
            {
                "step_number": 1,
                "asset_name": "prod-api-gateway",
                "technique_id": "T1190",
                "technique_name": "Exploit Public-Facing Application",
                "description": "CVE-2023-44487 (HTTP/2 Rapid Reset) exploited for initial access and RCE",
            },
            {
                "step_number": 2,
                "asset_name": "aws-s3-data-bucket",
                "technique_id": "T1530",
                "technique_name": "Data from Cloud Storage Object",
                "description": "EC2 instance metadata service used to steal S3 access credentials and bucket enumeration",
            },
        ],
        "source_asset_id": None,
        "target_asset_id": None,
    },
]
